# Generated by Django 5.0.3 on 2024-03-12 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articuloblog',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes-blog'),
        ),
    ]
